// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNs9FUgXKbQSBRT_P4f7QoGf7drQiw04',
    appId: '1:926624379234:web:789b6911247626577abc3b',
    messagingSenderId: '926624379234',
    projectId: 'solex-app',
    authDomain: 'solex-app.firebaseapp.com',
    storageBucket: 'solex-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6zeJ9l4RDjCCk9dlcRcoQNTaxec-dF4',
    appId: '1:926624379234:android:7a63d4193e0db6437abc3b',
    messagingSenderId: '926624379234',
    projectId: 'solex-app',
    storageBucket: 'solex-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RXxqw91IpM1pSGNhIZ_A66j_ORZkpAA',
    appId: '1:926624379234:ios:c1ff2715a0e4bc3e7abc3b',
    messagingSenderId: '926624379234',
    projectId: 'solex-app',
    storageBucket: 'solex-app.firebasestorage.app',
    iosBundleId: 'com.example.solexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RXxqw91IpM1pSGNhIZ_A66j_ORZkpAA',
    appId: '1:926624379234:ios:c1ff2715a0e4bc3e7abc3b',
    messagingSenderId: '926624379234',
    projectId: 'solex-app',
    storageBucket: 'solex-app.firebasestorage.app',
    iosBundleId: 'com.example.solexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNNs9FUgXKbQSBRT_P4f7QoGf7drQiw04',
    appId: '1:926624379234:web:03a25782cfe14b307abc3b',
    messagingSenderId: '926624379234',
    projectId: 'solex-app',
    authDomain: 'solex-app.firebaseapp.com',
    storageBucket: 'solex-app.firebasestorage.app',
  );
}
